apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-demo
spec:
  selector:
    app: nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}